function transpose_fpgaIO_setup(hFPGA,frameSize)
%--------------------------------------------------------------------------
% Software Interface Script Setup
% 
% Generated with MATLAB 9.10 (R2021a) at 19:37:54 on 13/06/2021.
% This function was created for the IP Core generated from design 'ddrxpose_21a_generic_fft_rdy2'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4", ...
	"BaseAddress", 0xA0000000, ...
	"AddressRange", 0x10000);

hPort_inputImageDDROffset = hdlcoder.DUTPort("inputImageDDROffset", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,32,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x100");

hPort_ddrDoneCounter = hdlcoder.DUTPort("ddrDoneCounter", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,32,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x104");

hPort_fifo_full_event = hdlcoder.DUTPort("fifo_full_event", ...
	"Direction", "OUT", ...
	"DataType", numerictype(0,32,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x108");

mapPort(hFPGA, [hPort_inputImageDDROffset, hPort_ddrDoneCounter, hPort_fifo_full_event]);

%% AXI4-Stream DMA
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream DMA", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 64, ...
	"WriteFrameLength", frameSize, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 64, ...
	"ReadFrameLength", frameSize,...
    'WriteTimeout',0,...
    'ReadTimeout',0);

hPort_DataIn = hdlcoder.DUTPort("DataIn", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,64,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream DMA");

hPort_tdata_o = hdlcoder.DUTPort("tdata_o", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,64,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream DMA");

mapPort(hFPGA, [hPort_DataIn, hPort_tdata_o]);

end
